#2026-08-01 09:47:04,310+0000
#Sat Aug 01 09:47:04 GMT 2026
@BlobStore.blob-name=health-check/nuget.org-proxy/summary/value_mask_sml.png
@BlobStore.created-by=repository-health-check
@BlobStore.direct-path=true
creationTime=1785577624310
sha1=f90c965fcda36ad1ba2c3d94c11b471518abc5e9
size=3278
