apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-deployment
  namespace: dev-project
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: backend-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-api
          image: dimakhot/backend-app:95fb71ba371477c6192f87262e2d4e53ebba5760
          ports:
            - containerPort: 8085
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MONGO_URI
