apiVersion: v1
kind: Secret
metadata:
    name: backend-secret
    namespace: dev-project
    annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
data:
    MONGO_URI: bW9uZ29kYjovL3VzZXJuYW1lOnBhc3N3b3JkQG1vbmdvLXN0YXRlZnVsLXNldC0wLm1vbmdvZGItaGVhZGxlc3MuZGV2LXByb2plY3Quc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcsbW9uZ28tc3RhdGVmdWwtc2V0LTEubW9uZ29kYi1oZWFkbGVzcy5kZXYtcHJvamVjdC5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNyxtb25nby1zdGF0ZWZ1bC1zZXQtMi5tb25nb2RiLWhlYWRsZXNzLmRldi1wcm9qZWN0LnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3Lz9yZXBsaWNhU2V0PXJzMCZhdXRoU291cmNlPWFkbWlu