apiVersion: v1
kind: Secret
metadata:
  name: argo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: aHR0cHM6Ly9naXRodWIuY29tL0RtaXRyaXlLaG90ZW1seWFuc2tpeS9pbmZyYS1yZXBv
  username: RG1pdHJpeUtob3RlbWx5YW5za2l5
  password: Z2hwX2kzdHVQQ0hhT1dHNFlzUFVBSDhQb204aTBITXNydDQ4YnFVVA==
