apiVersion: v1
kind: Namespace
metadata:
  name: dev-project
---
apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
    namespace: dev-project
    annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU=
    mongo-root-password: cGFzc3dvcmQ=
    mongo-express-username: dXNlcm5hbWU=
    mongo-express-password: cGFzc3dvcmQ=
    mongodb-keyfile: b0RRUURuZUJyZndJdkFrcXp6NmhPZytjL1daYWhNNVZVbkw2blU5eDlKQi9ubEZxUlVVb25KNHRQTEp1WjlmKytwSkdUK25ackJLUzVxT2FuRkx6UkVrUVAwTytaV1BrWHcrcXlwL0R5bTZqOTFpNW90a3JIdGE0YmpKd3JibFBXWm5VRGx1SU14K0J3Ty9jeGtaZUNZZjVpcFVxQllyR0tRQmxHYWdoNVEya3FBdDliQ0lHeHFIZmZiWDNJRjdTUVAwbnZ5Tno3cVNTbGFPY2VURUhKOU1HY2JEZjRCOUN6SDMrbEdVNmJnaTZhZHhUaitqVU1OWWhXdkhQWXdHaUkwZzRnRGVhUG0xYlk2NmsvK0NqYmZkdmtMNDFheVUxdUo5MTMwaVR4eTFVODhkZ2lSdDJTUlNnOUk5U09BTDBMdkRlNmw4Y2JyVUp2ZEJXSEtnK1hxemY1T3VCZDVZTmRobWYvVEhPaHZnMzdCZ1hIQXhPTHdGVU1iMGlERW9wTEI1dXNOLzdwdWNXWnlWOXYyQUFRU0twVVN0dnJDZzVHdlB6N21OTHg4eFlJQzdYazJmZE9DMWZka1VGREIzTXNoSkhIRHZvSmc2TWJvU2kwMXJpQmoreXIrSGRLMDVzaW9JUVpYb0pKV29HaUZyNWZtOHg4WjdxRkk4ek5QcSt5Z2RHNW9tR3lTZHAxektKSUNPWUhXMnFSbXpubmh3aHcwNlZRWVlnZWs4WnRvcGJmYlRuTVdEK2pFZVBqdVJyaEd0eG14QmtkVXlycWZQNzJOVlU0eWZXY3pVYmlPdVNiN3hlcGhJSlh2anhhNVV6bithc2dZU3FtUCsvS2hTc0dLQlh6WmRiVElsMXlNWGdUUFNnT2NYZ3hXK1E2K01IdmJnNDhyQzBFU0F3UHpCSnR2Q0Jzb1QzSG9QbHB0eVZIRVJIdjNEdHZicWZVZFhUL05DYTgyWVVXS0twMFZXdEpvYkF6MmhGbmhlVjdXWkVXWnZRaFJpeDVTMkNIRzdnbU8wWUExcFBJcGFzVmQ2QWpaTTkrTjhsNTlpR2ZCbzdhZXNnTWFvanlPQVZHYnYyS0tqcktHT0pORkNrZFc0MXMzOHBjOW9HSUFJQTFWWHVDTHZFdnlMNHY1NitHME9iSENjWXhEcW9JZStzVWpJMVdvZHc0QW9pcTI1MURiUjNwdHlNWUVGOTBxMFNoUmhzOXlvWEltMVhJRmRoeWhqUmY3NDEyK28yS3NiQUxYSlZnWDl6cTdKbVRLYVhnUmM2NndTZ3F0dC9xRlVCb1puQyt2Y0dYOXpoZ3VGY3I1V2lnVlA3TDlZVTM4clJmTTZ6