apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: dev-project
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: mongodb
spec:
  clusterIP: None
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb