apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deployment
  namespace: dev-project
  labels:
    app: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-app
          image: dimakhot/frontend-py3-app:8f9ec6d0f2975af2202b3de941fb96a2e55ccb0f
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: API_URL
